version: '3.8'

networks:
  test_developer:
    driver: bridge

volumes:
  test_developer_data:

services:

  backend:
    build:
      context: ./backend
    container_name: ${BACKEND_CONTAINER_NAME}
    command: python manage.py runserver 0.0.0.0:${BACKEND_PORT_HOST}
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT_HOST}:${BACKEND_PORT_CONTAINER}"
    networks:
      - test_developer

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    container_name: ${FRONTEND_CONTAINER_NAME}
    restart: always
    ports:
      - "${FRONTEND_PORT_HOST}:${FRONTEND_PORT_CONTAINER}"
    networks:
      - test_developer